version: 2.1
jobs:
  deploy:
    docker:
      - image: cimg/node:16.14.0
    steps:
      - add_ssh_keys:
          fingerprints:
            - $FINGERPRINTS
      - run:
          name: Pull code and start api_services
          command: ssh -o StrictHostKeyChecking=no $AWS_SERVER_USER@$AWS_SERVER_HOSTNAME 'cd sumika-stub && git pull origin main && npm install && pm2 reload app.js'

workflows:
  version: 2
  my-flow:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - main
