version: 2.1
jobs:
  deploy:
    docker:
      - image: cimg/node:16.14.0
    steps:
      - add_ssh_keys:
          fingerprints:
            - $FINGERPRINTS
      - run:
          name: pull code and start api_services
          command: ssh -oStrictHostKeyChecking=no $AWS_SERVER_USER@$AWS_SERVER_HOSTNAME "cd express-demo; git pull origin main; npm install; pm2 reload express-demo"
workflows:
  my-flow:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - main
