version: 2.1
orbs:
  node: circleci/node@4.7
jobs:
  deploy:
    machine:
      enabled: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - "9a:fb:eb:dc:a0:e5:95:4e:e2:a1:6f:87:0b:a3:23:e7"
      - run:
          name: pull code and start api_services
          command: ssh -oStrictHostKeyChecking=no ec2-user@ec2-13-213-10-195.ap-southeast-1.compute.amazonaws.com "cd express-demo; git pull origin main; npm install; pm2 reload express-demo"
workflows:
  my-flow:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - main
